// Hashes of prebuilt ghostty-vt binaries for each platform.
// Used by the build hook to verify downloaded artifacts.
//
// Generated by tool/write_asset_hashes.dart

// dart format off

/// The GitHub release tag from which prebuilt binaries are downloaded.
const String releaseTag = 'v0.0.3';

/// Maps platform labels to artifact info and SHA256 hashes.
const Map<String, AssetHash> assetHashes = {
  'linux-x64': AssetHash(
    tarball: 'vte-linux-x64.tar.gz',
    hash: '7c45562854e42660869a0c1829ceb3da7e98a03b951dec41ae7d5f8832f33b74',
  ),
  'linux-arm64': AssetHash(
    tarball: 'vte-linux-arm64.tar.gz',
    hash: '7b51abc1d982d1c6a964f8e50a24af4191bbd47fc9062005674f9a44a87dbaaa',
  ),
  'macos-arm64': AssetHash(
    tarball: 'vte-macos-arm64.tar.gz',
    hash: '044709fb74b9191182b827236999c4e0033a0d74792f1cbe3b13ac008f2bcec1',
  ),
  'macos-x64': AssetHash(
    tarball: 'vte-macos-x64.tar.gz',
    hash: '5a0162bb11c37acf8a9d4d0ff7d538349020db5e09173dc369aa831048261718',
  ),
  'windows-x64': AssetHash(
    tarball: 'vte-windows-x64.tar.gz',
    hash: '05121b91b3e701ee64c1ccde3c7d3c34c8ce3ce705ba6f9fb4d6e24a59570c2e',
  ),
  'windows-arm64': AssetHash(
    tarball: 'vte-windows-arm64.tar.gz',
    hash: '0fb8020d4e03c3e65cb80a14f01ee6fb0d0f1dbaf43d5df5d6413cf64063746f',
  ),
  'android-arm64': AssetHash(
    tarball: 'vte-android-arm64.tar.gz',
    hash: 'ab9f2ef75cdd77df05063d0d406992956e36b1f95fb0c282291c3860a90118c2',
  ),
  'android-arm': AssetHash(
    tarball: 'vte-android-arm.tar.gz',
    hash: 'fe9c638f7c2eb6a1e431d8be52e4f97f6c04c41a7c412746f6378be3c58235d4',
  ),
  'android-x64': AssetHash(
    tarball: 'vte-android-x64.tar.gz',
    hash: '595c9a5efdd807fd4b1652a23ce13306526e9da2edf36013feda8deedc3d8fdc',
  ),
};

/// Describes a prebuilt artifact with its download filename and integrity hash.
class AssetHash {
  /// The tarball filename in the GitHub release (e.g. "vte-linux-x64.tar.gz").
  final String tarball;

  /// SHA256 hash of the extracted library file.
  final String hash;

  const AssetHash({required this.tarball, required this.hash});
}
